## creating a dataframe

In [3]:
import pandas as pd

In [5]:
data = {
    "name": ["rahul","anu","john"],
    "age":[20,21,19],
    "marks":[85,98,78]
}
df=pd.DataFrame(data)
print(df)

    name  age  marks
0  rahul   20     85
1    anu   21     98
2   john   19     78

## accessing rows

In [8]:
print(df.loc[0])

name     rahul
age         20
marks       85
Name: 0, dtype: object

In [10]:
print(df.iloc[1])

name     anu
age       21
marks     98
Name: 1, dtype: object

## functions

## sum

In [14]:
(df["marks"].sum())

261

## avarage

In [21]:
(df["marks"].mean())

87.0

## maximum

In [28]:
(df["marks"].max())

98

## minimum

In [31]:
(df["marks"].min())

78

## filtering data

In [34]:
(df[df["marks"]>80])

    name  age  marks
0  rahul   20     85
1    anu   21     98

## adding new coloumn

In [54]:
df["Grade"] = ["B","A","C"]
(df)

    name  age  marks grde Grade
0  rahul   20     85    B     B
1    anu   21     98    A     A
2   john   19     78    C     C

## deleting coloumn

In [56]:
df=df.drop("Grade", axis=1)
df

    name  age  marks grde
0  rahul   20     85    B
1    anu   21     98    A
2   john   19     78    C

## saving a dataframe

In [64]:
df.to_csv("students.csv", index=False)