In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("fifa_world cup.csv")

In [3]:
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,

In [4]:
df.tail()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
1069,2026.0,NaN,Quarter-finals,GEHA Field at Arrowhead Stadium,Kansas City,Argentina,3.0,1.0,Switzerland,Argentina win after extra time
1070,2026.0,NaN,Semi-finals,AT&T Stadium,Dallas,France,0.0,2.0,Spain,
1071,2026.0,NaN,Semi-finals,Mercedes-Benz Stadium,Atlanta,England,1.0,2.0,Argentina,
1072,2026.0,NaN,Third Place,Miami Stadium,Miami,France,4.0,6.0,England,
1073,2026.0,NaN,Finals,New York New Jersey Stadium,New Jersey,Spain,1.0,0.0,Argentina,Spain win after extra time

In [5]:
df.shape

(1074, 10)

In [6]:
df.size

10740

In [7]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions'],
      dtype='object')

In [8]:
df.dtypes

Year               float64
Datetime            object
Stage               object
Stadium             object
City                object
Home Team Name      object
Home Team Goals    float64
Away Team Goals    float64
Away Team Name      object
Win conditions      object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             1074 non-null   float64
 1   Datetime         980 non-null    object
 2   Stage            1074 non-null   object
 3   Stadium          1074 non-null   object
 4   City             1074 non-null   object
 5   Home Team Name   1074 non-null   object
 6   Home Team Goals  1074 non-null   float64
 7   Away Team Goals  1074 non-null   float64
 8   Away Team Name   1074 non-null   object
 9   Win conditions   1074 non-null   object
dtypes: float64(3), object(7)
memory usage: 84.0+ KB

In [10]:
df.describe()

              Year  Home Team Goals  Away Team Goals
count  1074.000000      1074.000000      1074.000000
mean   1992.830540         1.761639         1.059590
std      25.143376         1.584812         1.091433
min    1930.000000         0.000000         0.000000
25%    1974.000000         1.000000         0.000000
50%    1998.000000         1.000000         1.000000
75%    2014.000000         3.000000         2.000000
max    2026.000000        10.000000         7.000000

In [11]:
df=df.drop("Datetime",axis=1)
print(df)

        Year           Stage                          Stadium         City  \
0     1930.0         Group 1                          Pocitos  Montevideo
1     1930.0         Group 4                   Parque Central  Montevideo
2     1930.0         Group 2                   Parque Central  Montevideo
3     1930.0         Group 3                          Pocitos  Montevideo
4     1930.0         Group 1                   Parque Central  Montevideo
...      ...             ...                              ...          ...
1069  2026.0  Quarter-finals  GEHA Field at Arrowhead Stadium  Kansas City
1070  2026.0     Semi-finals                     AT&T Stadium       Dallas
1071  2026.0     Semi-finals            Mercedes-Benz Stadium      Atlanta
1072  2026.0     Third Place                    Miami Stadium        Miami
1073  2026.0          Finals      New York New Jersey Stadium   New Jersey

     Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0            France              4.0              1.0         Mexico
1               USA              3.0              0.0        Belgium
2        Yugoslavia              2.0              1.0         Brazil
3           Romania              3.0              1.0           Peru
4         Argentina              1.0              0.0         France
...             ...              ...              ...            ...
1069      Argentina              3.0              1.0    Switzerland
1070         France              0.0              2.0          Spain
1071        England              1.0              2.0      Argentina
1072         France              4.0              6.0        England
1073          Spain              1.0              0.0      Argentina

                      Win conditions
0
1
2
3
4
...                              ...
1069  Argentina win after extra time
1070
1071
1072
1073      Spain win after extra time

[1074 rows x 9 columns]

In [12]:
df.head()

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930.0,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,
1,1930.0,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,
2,1930.0,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,
3,1930.0,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,
4,1930.0,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,

In [13]:
df.tail()

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
1069,2026.0,Quarter-finals,GEHA Field at Arrowhead Stadium,Kansas City,Argentina,3.0,1.0,Switzerland,Argentina win after extra time
1070,2026.0,Semi-finals,AT&T Stadium,Dallas,France,0.0,2.0,Spain,
1071,2026.0,Semi-finals,Mercedes-Benz Stadium,Atlanta,England,1.0,2.0,Argentina,
1072,2026.0,Third Place,Miami Stadium,Miami,France,4.0,6.0,England,
1073,2026.0,Finals,New York New Jersey Stadium,New Jersey,Spain,1.0,0.0,Argentina,Spain win after extra time

In [14]:
df.isnull().sum()

Year               0
Stage              0
Stadium            0
City               0
Home Team Name     0
Home Team Goals    0
Away Team Goals    0
Away Team Name     0
Win conditions     0
dtype: int64

In [15]:
df.duplicated().sum()

16

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.duplicated().sum()

0

In [18]:
df["Year"]

0       1930.0
1       1930.0
2       1930.0
3       1930.0
4       1930.0
         ...
1069    2026.0
1070    2026.0
1071    2026.0
1072    2026.0
1073    2026.0
Name: Year, Length: 1058, dtype: float64

In [19]:
df[["Year","Stage","Stadium"]]

        Year           Stage                          Stadium
0     1930.0         Group 1                          Pocitos
1     1930.0         Group 4                   Parque Central
2     1930.0         Group 2                   Parque Central
3     1930.0         Group 3                          Pocitos
4     1930.0         Group 1                   Parque Central
...      ...             ...                              ...
1069  2026.0  Quarter-finals  GEHA Field at Arrowhead Stadium
1070  2026.0     Semi-finals                     AT&T Stadium
1071  2026.0     Semi-finals            Mercedes-Benz Stadium
1072  2026.0     Third Place                    Miami Stadium
1073  2026.0          Finals      New York New Jersey Stadium

[1058 rows x 3 columns]

In [20]:
df.iloc[0]

Year                    1930.0
Stage                  Group 1
Stadium                Pocitos
City               Montevideo
Home Team Name          France
Home Team Goals            4.0
Away Team Goals            1.0
Away Team Name          Mexico
Win conditions
Name: 0, dtype: object

In [21]:
df.iloc[0:5]

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930.0,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,
1,1930.0,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,
2,1930.0,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,
3,1930.0,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,
4,1930.0,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,

In [22]:
df.iloc[0,1:4]

Stage          Group 1
Stadium        Pocitos
City       Montevideo
Name: 0, dtype: object

In [23]:
a=df.groupby("Home Team Name")["Home Team Goals"].sum()
a

Home Team Name
Algeria                         5.0
Angola                          0.0
Argentina                     133.0
Australia                      11.0
Austria                        34.0
                              ...
rn">Bosnia and Herzegovina      3.0
rn">Republic of Ireland         2.0
rn">Serbia and Montenegro       0.0
rn">Trinidad and Tobago         0.0
rn">United Arab Emirates        0.0
Name: Home Team Goals, Length: 92, dtype: float64

In [24]:
a.sort_values(ascending=False)

Home Team Name
Brazil                       196.0
Argentina                    133.0
France                       101.0
Italy                         99.0
Germany FR                    99.0
                             ...
Cabo Verde                     0.0
Angola                         0.0
rn">Serbia and Montenegro      0.0
rn">Trinidad and Tobago        0.0
rn">United Arab Emirates       0.0
Name: Home Team Goals, Length: 92, dtype: float64

In [25]:
b=df.groupby("Away Team Name")["Away Team Goals"].sum()
b

Away Team Name
Algeria                        8.0
Angola                         1.0
Argentina                     33.0
Australia                      9.0
Austria                       12.0
                              ...
rn">Bosnia and Herzegovina     1.0
rn">Republic of Ireland        8.0
rn">Serbia and Montenegro      2.0
rn">Trinidad and Tobago        0.0
rn">United Arab Emirates       2.0
Name: Away Team Goals, Length: 96, dtype: float64

In [26]:
b.sort_values(ascending=False)

Away Team Name
France                     52.0
Brazil                     51.0
Spain                      51.0
England                    47.0
Mexico                     43.0
                           ...
Iraq                        0.0
Zaire                       0.0
Bolivia                     0.0
rn">Trinidad and Tobago     0.0
Türkiye                     0.0
Name: Away Team Goals, Length: 96, dtype: float64

In [27]:
extra = df["Win conditions"].str.contains("extra time", case=False).sum()
penalties = df["Win conditions"].str.contains("penalties", case=False).sum()

print("Extra Time :", extra)
print("Penalties :", penalties)

Extra Time : 34
Penalties : 39

In [28]:
df["Home Team Goals"].value_counts()

Home Team Goals
1.0     312
2.0     248
0.0     228
3.0     140
4.0      70
5.0      22
6.0      21
7.0      10
8.0       4
9.0       2
10.0      1
Name: count, dtype: int64

In [29]:
a=df["City"].value_counts()
a

City
Mexico City        23
Al Rayyan          23
Montevideo         18
Guadalajara        17
Rio De Janeiro     15
                   ..
Antibes             1
Lugano              1
Eskilstuna          1
Orebro              1
Foxborough          1
Name: count, Length: 187, dtype: int64

In [30]:
a.max()

23

In [31]:
a=df.groupby("Home Team Name")["Away Team Name"].value_counts()
a

Home Team Name             Away Team Name
Algeria                    Austria             1
                           Chile               1
                           Northern Ireland    1
                           Russia              1
                           Slovenia            1
                                              ..
rn">Republic of Ireland    Norway              1
                           Romania             1
rn">Serbia and Montenegro  Netherlands         1
rn">Trinidad and Tobago    Sweden              1
rn">United Arab Emirates   Colombia            1
Name: count, Length: 833, dtype: int64

In [32]:
a=df.groupby("Stage")["Win conditions"].value_counts()
a

Stage              Win conditions
Final                                                  12
                   Argentina win after extra time       1
                   Brazil win on penalties (3 - 2)      1
                   England win after extra time         1
                   Germany win after extra time         1
                                                       ..
round of 16        Morocco win on penalties (3 - 0)     1
                   Russia win on penalties (4 - 3)      1
semi-finals                                             3
                   Croatia win after extra time         1
third-place match                                       2
Name: count, Length: 103, dtype: int64

In [33]:
df[df["Stage"]=="Final"]

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
17,1930.0,Final,Estadio Centenario,Montevideo,Uruguay,4.0,2.0,Argentina,
34,1934.0,Final,Nazionale PNF,Rome,Italy,2.0,1.0,Czechoslovakia,Italy win after extra time
52,1938.0,Final,Stade Olympique,Colombes,Italy,4.0,2.0,Hungary,
100,1954.0,Final,Wankdorf Stadium,Berne,Germany FR,3.0,2.0,Hungary,
135,1958.0,Final,Rasunda Stadium,Solna,Brazil,5.0,2.0,Sweden,
167,1962.0,Final,Nacional,Santiago De Chile,Brazil,3.0,1.0,Czechoslovakia,
199,1966.0,Final,Wembley Stadium,London,England,4.0,2.0,Germany FR,England win after extra time
231,1970.0,Final,Estadio Azteca,Mexico City,Brazil,4.0,1.0,Italy,
269,1974.0,Final,Olympiastadion,Munich,Netherlands,1.0,2.0,Germany FR,
307,1978.0,Final,El Monumental - Estadio Monumental Antonio Ves...,Buenos Aires,Argentina,3.0,1.0,Netherlands,Argentina win after extra time
359,1982.0,Final,Santiago Bernabeu,Madrid,Italy,3.0,1.0,Germany FR,
411,1986.0,Final,Estadio Azteca,Mexico City,Argentina,3.0,2.0,Germany FR,
463,1990.0,Final,Stadio Olimpico,Rome,Germany FR,1.0,0.0,Argentina,
515,1994.0,Final,Rose Bowl,Los Angeles,Brazil,0.0,0.0,Italy,Brazil win on penalties (3 - 2)
579,1998.0,Final,Stade de France,Saint-Denis,Brazil,0.0,3.0,France,
643,2002.0,Final,International Stadium Yokohama,Yokohama,Germany,0.0,2.0,Brazil,
707,2006.0,Final,Olympiastadion,Berlin,Italy,1.0,1.0,France,Italy win on penalties (5 - 3)
771,2010.0,Final,Soccer City Stadium,Johannesburg,Netherlands,0.0,1.0,Spain,Spain win after extra time
828,2014.0,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time

In [34]:
df["Home Team Goals"].max()

10.0

In [35]:
df["Home Team Goals"].min()

0.0

In [36]:
df["Away Team Goals"].max()

7.0

In [37]:
df["Away Team Goals"].min()

0.0

In [38]:
df["Total goals"]=df["Home Team Goals"]+df["Away Team Goals"]

In [39]:
df.head()

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Total goals
0,1930.0,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,5.0
1,1930.0,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,3.0
2,1930.0,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,3.0
3,1930.0,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,4.0
4,1930.0,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,1.0

In [90]:
def Winner(row):
    if row["Home Team Goals"]> row ["Away Team Goals"]:
        return row["Home Team Name"]
    elif row["Home Team Goals"] < row ["Away Team Goals"]:
        return row["Away Team Name"]
    else :
        return "Draw"
df["Winner"]=df.apply(Winner,axis=1)

In [96]:
df.sample(5)

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Total goals,Winner
360,1986.0,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,2.0,Draw
42,1938.0,First round,Stade Municipal,Toulouse,Cuba,2.0,1.0,Romania,,3.0,Cuba
728,2010.0,Group D,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Germany,0.0,1.0,Serbia,,1.0,Serbia
359,1982.0,Final,Santiago Bernabeu,Madrid,Italy,3.0,1.0,Germany FR,,4.0,Italy
760,2010.0,Round of 16,Durban Stadium,Durban,Netherlands,2.0,1.0,Slovakia,,3.0,Netherlands

In [94]:
wins=df["Winner"].value_counts()
print(wins)

Winner
Draw              235
Brazil             79
Argentina          52
Italy              45
France             44
                 ...
Czech Republic      1
Jamaica             1
Cuba                1
Wales               1
Türkiye             1
Name: count, Length: 73, dtype: int64

In [98]:
df.to_csv("new_fifa_world_cup.csv",index=False)